### ISSUE TITLE
ImportError: libgfortran.so.1

### ISSUE THREAD

**Issue by sean-ocall** [METASPACE2020/sm-engine-ansible#12]
Hi guys,
I'm getting an error when I try to run the spheroid test. Full error message here:

(sm)ubuntu@vagrant-ubuntu-trusty-64:/opt/dev/sm$ scripts/run.sh scripts/run_molecule_search.py spheroid /opt/dev/sm/tests/data/sci_test_search_job_spheroid_dataset/ /opt/dev/sm/tests/data/sci_test_search_job_spheroid_dataset/config.json
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgfortran.so.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgfortran.so.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgfortran.so.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgfortran.so.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgfortran.so.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Traceback (most recent call last):
  File "scripts/run_molecule_search.py", line 10, in <module>
    from sm.engine.search_job import SearchJob
  File "/opt/dev/miniconda/envs/sm/lib/python2.7/site-packages/sm/engine/search_job.py", line 15, in <module>
    from sm.engine.msm_basic.msm_basic_search import MSMBasicSearch
  File "/opt/dev/miniconda/envs/sm/lib/python2.7/site-packages/sm/engine/msm_basic/msm_basic_search.py", line 2, in <module>
    from sm.engine.msm_basic.formula_img_validator import sf_image_metrics, sf_image_metrics_est_fdr
  File "/opt/dev/miniconda/envs/sm/lib/python2.7/site-packages/sm/engine/msm_basic/formula_img_validator.py", line 8, in <module>
    from pyImagingMSpec.image_measures import isotope_image_correlation, isotope_pattern_match
  File "/opt/dev/miniconda/envs/sm/lib/python2.7/site-packages/pyImagingMSpec/image_measures.py", line 2, in <module>
    import scipy.stats
  File "/opt/dev/miniconda/envs/sm/lib/python2.7/site-packages/scipy/stats/**init**.py", line 321, in <module>
    from .stats import *
  File "/opt/dev/miniconda/envs/sm/lib/python2.7/site-packages/scipy/stats/stats.py", line 180, in <module>
    import scipy.special as special
  File "/opt/dev/miniconda/envs/sm/lib/python2.7/site-packages/scipy/special/**init**.py", line 601, in <module>
    from ._ufuncs import *
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory

Looks like it's some sort of scipy issue from a quick google search.

**Comment by lomereiter** [comment]
Hi, I googled a bit and it looks like https://github.com/ContinuumIO/anaconda-issues/issues/686

The suggested workaround is to run `conda install -f libgfortran==1`

**Comment by sean-ocall** [comment]
Hi,

I should have said - I did try that (and have done so again), unfortunately it doesn't fix it, and the error message is the same.
Thanks,
Sean

**Comment by lomereiter** [comment]
Hi,
Apparently some nasty package sets `LD_PRELOAD` to point to system-wide installation of `libgfortran3`, and it is not installed. Please try running `apt-get install libgfortran3`, hopefully it'll help.

**Comment by sean-ocall** [comment]
Yes, that did it!
